apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:BSSCF7naUj8QAsTBHN4+1A0XxU+1N3GoWzfa4ZKsXNaqpRaLU8VNnA==,iv:EBy1HcpLe17ORSeaovbetTZYIF7kVbbmYtX5A95u940=,tag:d8uSH7UieV4QMRNdUbDxEw==,type:str]
sops:
  age:
    - recipient: age1yzx80evlzvlvmepvta9mscwg8wkwhnky8mla5q2qsjd5afp8nyfstw5x5h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5WldPeG0wak83VU4yVVpw
        K1had2pPUGErU3pDNnZPVVkyM1MxZG9GMmlzCnB2ODZNbE13dWc3bXpCMHNhQisr
        UEJrSDVERVpmTmNFdFcwMUcyWE9UejAKLS0tIGd4MEJJSVgrNzNmZUlIMGZGZWdi
        Mk1pOTVyODV3TURyejJHNGYxK2FZS3MKiBS4C0UI4x8dxdysU/2HgJHboutszhrb
        xRoNKoh4k+gt93hqp/VfsIg/goWP44M0pL9T8G9+DnPxSydA6B0b3A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T09:40:18Z"
  mac: ENC[AES256_GCM,data:iJpMSr8twi9Tr+LcxaEcpM3fnsbFxADwJGy2BdsYe41M4wBuf/ad/suQZisw5wHG4QNxHMtGTuDcSMjYbpr9mIysyb54H/lGueGlv9uOOYT3I8hTjYU5jz5xI6xrbFMSoHD+6bz0bIvWdvLXU/IIO38kt2iqTlTuMVBcJgU2xlE=,iv:SDjBYcUrlVpvISXSQWdeDugR1nEdRzT/E52rHYoT4YE=,tag:S5InTEmwg4+8FX8g4ms/3A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
