apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:KxTC5ofQXWc72lraHVkFWSG414/SU0XRxLBBl/6b6W4c3EmFEsmu3w==,iv:bit3POwvx1CTYdiKo2JUvRzup08/2HEfDfrQkkvtTF0=,tag:erxCaWsrowB4WagGmiOpgw==,type:str]
sops:
  age:
    - recipient: age1yzx80evlzvlvmepvta9mscwg8wkwhnky8mla5q2qsjd5afp8nyfstw5x5h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4N21QQ2hlckhEYW8yTVA3
        bkdqZ1pQUEFFcDlWdzI3QkxwVkYvSnZvZDNVClZTM2Evc1laK0ZNa0NlM3FQVTRO
        dkRlbmVGUGZHQUJCSVBTNjF4MVk4L28KLS0tIE1kbmNXbEI4T0o2STR0NVg3OWFS
        c2dHcjRZenRTVG1GZU10OFQvVDc5S28Kng67seRwzlUw98ZV6mJALorhJDbF+Vj1
        l1EFB4viHYUCj7KIedrZvhpXDAUETCwcyhQLzkTrLzJZ8l6xJurnpg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-13T08:17:47Z"
  mac: ENC[AES256_GCM,data:PFXd6TPT9KfU0GcL3CTTygIso8ktPM6iYmdZWIK3K48FZWH6IwT0goPBPqcfGJx9ocQW6UHulFQt9u9PM8xU19UA0k1sffNt2xExaoS9LqmeFuMPfnenn5l1pj/1dByW0vAqv9pZdSnMRe21i4dPBV0KleCRnbBMsLHhEpX+8XA=,iv:U5XhlHO0z+XSyBJmKYOxHAylvL7sBMSJByOc/lBWfsQ=,tag:JTJczakdpZyfMZfrjypLkw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
