# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-idrive-secret
  labels:
    app.kubernetes.io/name: ${APP}
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:DxkAhmnBD4qKC+rHBVJrq/8KFHnET7dNddqc+ncmk8cfC2XxunbbgYiCxs57mA==,iv:ItF4DWyDgyPJ3ZiErXhlXLVKQUapdEuU15rrOlw8qj0=,tag:fhLOL8mN/2fo+1qGNkR1xQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:iOaniAaDOBKZFr7y+oCjDb8rMZ0V9A==,iv:ofUN8KpfndPyVeG7UZglvzxTMr/aY6v1nhEI83rSi3w=,tag:uqdjvegxYYPFUkovn6UFsg==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:2Jfi07zGr/M+u6Mtlaz1l00n5oo=,iv:V9Dot7HZhhILZkFNtdW4IJJIBqaCpKXzL9CiUs3GjY4=,tag:71/3bgP9AnnyPh2zLsmnKA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:TI9VBymSDAfjP84wiKuz4i63CLZTaEwIBQke0dQwyLdphXGwedHSlA==,iv:zvTmUQxhPQyJ5ha4U2L9mmKj4iBEz6G+YXs7X+6U+0s=,tag:j7EZjPT6hgm5eja/aYv01w==,type:str]
  RESTIC_PACK_SIZE: ENC[AES256_GCM,data:mDM=,iv:Oz17mnKlbc/sI+auUoBtWCjTV69OIaLtYXPCO3XWwCw=,tag:CEYZnRyU3QE9/P5FB7pz5g==,type:str]
sops:
  age:
    - recipient: age1yzx80evlzvlvmepvta9mscwg8wkwhnky8mla5q2qsjd5afp8nyfstw5x5h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZG56WnhKYlZHc3diWGM4
        TXFCWmlxSzVsdFN3ZDUyY01JQURPQ2JRVkU0Clg0OE1SODJ4RHlldGlTbUJMS0Zn
        VkxlQU05V1F3TEIwb0FTbU9DMjNmcVUKLS0tIHhVU3lQUVNvcFFhMDcvVG8vR3Bq
        QS8xZkg2ajlJRFI3RGN6b1VaUE92M0UKBCMAn204uWf/f2BB/9Gbk03cBAyPg+37
        kHktUldRWmGvPW1EMkHltOhwcsattsst0CtzXA8oGsrWJ/d+Ssu1cA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-28T21:35:53Z"
  mac: ENC[AES256_GCM,data:g+4rbCzzX7RgoUAPGjXUcciaSKxV8n6PGlANbGny2EkJQOguLFFK/Wwq1RlQgWINI76Q8f6jxxQ3+sjfY5JczckQ3cD2LrgQ0h+fTISQn4gKJiaLlwradqKIgRO//9WHfxuwASTuNIW5SKHgI7yhD6O6H/O0E2jyeFnFIEsM8aI=,iv:INjVzibW6J/eWfoYPfygdA+YBGBOxMDIOn41FvoK2Yc=,tag:LKlQPd+H+z3nVcFzr6ntLg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
