apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:+kG9Fbwz2BiPi7qZ,iv:sp80UpB+0GrSbmldk3CJ9CiOZvQ3T9bFZoYj/jhAEEg=,tag:VA2K8XKYt0UrbN8xOUPMTA==,type:str]
sops:
  age:
    - recipient: age1yzx80evlzvlvmepvta9mscwg8wkwhnky8mla5q2qsjd5afp8nyfstw5x5h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SldnQzhnZWdqeTQwcnh0
        N3RWMXUwaUNQZDRwb0tkYlkzd2hSKzdGM3lnCnJYM0lMVkFLaHZiQ0RraTlEQ2Jz
        NU5FT2lQWEJhS0FIUUowbzF3Ky9Ld2MKLS0tIE5rMTU1V0dnelRtdU9hYzg3Sy83
        bGpTK1grMVRUZFJCWDZXcG81N0tmYmsKuv5kFVtUn/vw2ozcTfcF32uWEEkA9iBl
        wCX31I1Xv8GfWHeKVvtjWEUXmvjsdkvcUV2m1XnC/t9xxQYMe3GdYw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-13T08:17:47Z"
  mac: ENC[AES256_GCM,data:S23woUv2Uj+06hjG+24+MI+OoKgkahbioMHhZt//HyOmCLtK10laG3d8d1pe9UOx1YvXzjzuRUPCD1n1E84uNUaqAsLtULlSeg2sIjSnJ1b3UKTCm52WSkhU2oyoeBTmUuVpHPrzu+LJ8GVjCcRRTntEO4wFxMffuzNRq5XSD+0=,iv:tfjark1HEdKGWb0/1eAh+nQC30PQivAkrlCbn86TMeg=,tag:41cn39CVk1q7afWcW5OPgA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
