apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:X2jsvLj4wZo0AepE,iv:cMM+g0D8lyqInOwHRgINLPcY22ed/HyI/YnqJVwW2WI=,tag:V4y1fj6ky1n68CVGblZ+2w==,type:str]
sops:
  age:
    - recipient: age1yzx80evlzvlvmepvta9mscwg8wkwhnky8mla5q2qsjd5afp8nyfstw5x5h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZGJhUXNOZ3lTaG50WHRw
        TTYrY0VFRUNRSldQSytzd3N5MEk3WnRhblM4CkllYkZYUmNlNXdSSWZPZDJCdXl1
        dWNVS3NJMVFaSjNxR2pCdkJwMVhoMW8KLS0tIENhMDNxVnRwUjVXTDNuQzFEa1NG
        ZTNNZ0c4SjBrTThSbmxyUDVKVTV3TE0K2xKfQSILQCLZqoEBPTwSrn3gNDJhBdHV
        A6EwlgT508G0kVVPF6tbbabYI0scT2PFzSpD9gxwR8+oE+dy8QJlhw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T09:40:18Z"
  mac: ENC[AES256_GCM,data:reOvUc8BCxuV07UzzTpW8cmbtaQuP6N3RDoboQz6Hk0f/WZWYyDjh0Ck+mkx31EEF+UMiZSzCn4wi9fGZAmgfweW0Or4FgUKu/O97gpYMaqi7BoFWvXuLUP6GD6kwnPXSZ5/ixm/Pta3yzGS3xS0kdC5e6McLtD9kW0QXKS5M3I=,iv:fcN8xvKmVWULXEgCphYhFfRL2T4/+PZbAIMEgDXKb2s=,tag:/hCXcUxXDx1DSBLVHGCDTA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
