apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:3rD+XttCZSc2TEj7q3zxvMwwIpcWsV5DEoSRunnR8vo=,iv:a85DPtH1KkcrcDiXeCs9qHq2q42kd13mhLOUc1yFo5s=,tag:GkW4YDxTMSxxo31R5uotFQ==,type:str]
sops:
  age:
    - recipient: age1yzx80evlzvlvmepvta9mscwg8wkwhnky8mla5q2qsjd5afp8nyfstw5x5h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTTYwSmY1Yk42YlZneDFC
        WmxLN29BY3gzL2VubFZFVVQ5NE5zSUdSWm44CkNPQUx1MCtWOFZtcnhEN2lnK3FJ
        MHZZZmx0Z21yM3Vjb1JlZmtHRFVQZGMKLS0tIHNPSS9GQXJ0VHE1R0FONGlIUTdB
        V0xXVUtxaStnenczeVNaVzFvYTkyNzQKRMxUaEc+WyjPYwPAvZ7uxZl8Luy10N0C
        YL3owudS9qUoCIxXCU+omVCcUMfxPa+2dwL6Ay4ZOMw14O8oNiBm2Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-13T08:17:47Z"
  mac: ENC[AES256_GCM,data:/p3L3PiH9o/OJbyYZZehzVZP8CcGQ5R8opADl9ABBSdR0SJeH1plOowbNJapmSocNhH0hjKMrnSicJeK8teNHJRUd83LgT3ijop/t/3/llQXrO1cr/yVKLaMbwGy735V1oGwEkzE03TAVnREBfi3Ey9Et/0WSFq+giFSR/cJT/Q=,iv:yrZKESG20mAQzZWyktEgra2x504Eo+xuDq5u43IhKdE=,tag:60SJYjRscgBZM6MPfxhMHA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
