apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:QfpTT0wFWflaOhY/eUS7rYAv6iJJK6kqiIrHPAO0DI0=,iv:JqCPt7YiLuo/OaMEnYG90mkQTcZjpATwPRccE32YF9A=,tag:Dp/2PFeBszjGRcCEragu+A==,type:str]
sops:
  age:
    - recipient: age1yzx80evlzvlvmepvta9mscwg8wkwhnky8mla5q2qsjd5afp8nyfstw5x5h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWlBLQjNyblNjOTNnN0pB
        ZmhUSklNdllGaEkwOWp2R09OLzVCeTAzdEZVCi8xMVAwVk1FV2lZMTNCSGJWZU1L
        UXdVYksrUHMvMUMwT2lUVnYvemwwTUkKLS0tIE8xMW0zT2xyaUd6bjJiVVhwbkJn
        aG5ENGMvajZ2VGVsZlJkWEJPdzQ4VzQKYcANhBN7ywW8CQCEPuVNqQplEFmHfol4
        JE8bFNWVOH5mhC+qlkkbkL7mY0GKgUqtFmcIFU0PChB0ZeloW3a6Zg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T09:40:18Z"
  mac: ENC[AES256_GCM,data:f8d1FDHcVQGl29o5OQHKyZT68mM6d3K+sk2X8dKEoApwlN9DTrIOqR1jCdluqbW+zjhprxbh0qdwivVMN2j8zfq4xWyGMghfpZmka29Fv2wPdZ4/giRrHdsTUUSMcp8N/l2mpPQ/B1r9J8zEQ+qOlpFSobXsu44lV1oEzOxw4bc=,iv:fSlN2OmNcbV4PwLhGin4DRW69lClcZWz9Qy8gF5/eHY=,tag:rFCBaRxdNftJgvadDWJyqw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
