apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:c/4uDMHV/NvaIPzLSJ9jszj5AFiql5JnlaWRHKLvzzLkz7HUoc3xaqSrVVinOI2DXNUmtD1RItrRVNnEfPJkDrNr9Bs3X4uLnsLNkJRklAWeIr/KtWaEMmNHkFXfKqKE5xQAezyMrgFbj9Hhyf/Dyz3wUYQFdAagaBA4b5o1cDxgCaeMPUS+csOleu6/5KRbR0v2xBuYLnZhDw0h8e21WP3yDOO2cEyac37BoltjRH30PbxE,iv:e5lrF6mKz/FUK/31BXPKHgU+0wRIKSvA+vEV4MHR+CI=,tag:kgwK1dUafIn3JctMXlGpXQ==,type:str]
sops:
  age:
    - recipient: age1yzx80evlzvlvmepvta9mscwg8wkwhnky8mla5q2qsjd5afp8nyfstw5x5h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSUlLR2gxdlhHMjhpVjdx
        Q0JGaWtVdDJYbG4xM3FZVERSQkdsZ3pHZWhBCksvaGQ3TXp3SUpCM1kxZWpqUXhB
        WExhRHM5Yk50ckZpSnNCaVp6TS85eFUKLS0tIFMySUxHSmZ3OXA1THRhY2hYbjRV
        V3hFQ21EQ3VtcWVyR3lwelVwSGE0WkkKKsidII3gOH77/4EamOxo9zlaZsvhfeLj
        PUEoIRGQVS79CqYs5Q748PtvdYFesokZzPqSdhh1wr7kAUD6N85pPg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-13T08:17:47Z"
  mac: ENC[AES256_GCM,data:ycXU0sOKIIp6XlEDLOo9g6Fci9KMNy/J3R3WguPQR+kcRRagawhYEqMg4SURoJHnldzwKlwzP9fFbvFXdD51YlrNvS335ij+FOqkkll296vq6VBh6T6pXN3Y7faZIww+S2TFPX8IZaBkNkWtcWJPTdh4a1XLGP7gCrMrTqAxUTA=,iv:BSDhZOBBK6QcQXfDBXHZ498CYyzjeJdpk/qzaKj1u0E=,tag:S6IsAOT/2GUsY5yXB7J3EQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
