apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:kyWmuuU/giNliRKGKOQHTANE8G+phNgp6r2cnDxOG0uoSmWpeUgpNDgCk4+dHAyxXKwihfjPlDYRoSVjrR8zS2pY915mm38bD9ZRcnCbpAtu8CQy2tLr2y/DwB067Ifo0Sx1VZQmUvRG6O2ErF837NPLg/Cv6uubggicCDdwFOq7o1dk0moR4pLNJ/+9MwRTDAQkMkXwBH6n7DBxen54qle5ELpTGOoc7pO/vWL7d89WrmnN,iv:TFqRzZi0iPt1F76wrFFsFs/XihK2gJWB1G6ReUN6EFg=,tag:J5z5b0ZcDwcyoDkGM/w6PQ==,type:str]
sops:
  age:
    - recipient: age1yzx80evlzvlvmepvta9mscwg8wkwhnky8mla5q2qsjd5afp8nyfstw5x5h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlN20yTmZaQWxhNUFTMytt
        clUzZmdZWXllOGp1SUJPbGppRy8rYnNGemlNCndBQmxxQmNRTUExY2JRRjBpdUJy
        aGVPUFhoTFp5WFdtb0ZzMHFoZkxnTk0KLS0tIHhYS0RkS3ppK3FuVCtMN3prdWVt
        Z1BNejRSQ3pJd2h2WElEMGpWcXBJakEKku6MojdoOtxmfjzaB+rGgcXzJfqQRQxL
        Y3H0Ne7Pg3YK7/kCKrwQZ3c4TWaJroJMQ6s7FmRry0OqefdrTHV4yw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T09:40:18Z"
  mac: ENC[AES256_GCM,data:Lr6Mbj8h+yG71I1flc5dkoWH5zdTRfxYs8yVPZpfPlah8miiWV6AGvFAR1e3f55MGmOxZA10wUscpWAgcFRKbtn9Z2/M4cEPllH7NkH1YjAqVCFYnjhxsesquO5I9JLcfBT+/klddvs2GAdcocXXgWQSx8efR7Q7aoGI35gMom8=,iv:NQm80NABhRQN8AJi+H7TTmFpDkbEmxsQ2qKjOK3An24=,tag:8jOAnds+Q8SUxHmicvjgVQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
