apiVersion: v1
kind: Secret
metadata:
  name: unifi-dns-secret
stringData:
  UNIFI_API_KEY: ENC[AES256_GCM,data:joYQdS0zG4BXK9UHtd4obbOLJxN43hVuezq6L+krl2A=,iv:ldn8LauEcDjhhFc6t9KACEYQBzCU9wMQ0mxVrAJcAOg=,tag:mYX6g2NnWvy8WhozIUetyg==,type:str]
sops:
  age:
    - recipient: age1yzx80evlzvlvmepvta9mscwg8wkwhnky8mla5q2qsjd5afp8nyfstw5x5h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSYXQ4djJ4RUdFNzgyMG9G
        L0E1RzJyRXZMU2FDM0x4S3JkUWk4NWhMRXdVCmp0MmhWdzNJQzFxdWNFMEtwSEFX
        K2l3UUdKRVRwZnVhMU9BRWQ4UVJieGcKLS0tIEhmcWhhUzNBY3U2R04zNW16QnNJ
        NG5neW9zK2RvN0FqZVFhT3pQNG1ML0EKPxzcsqXixaMakmKdZT/R3tQt0Rn9VgD/
        jDJ495slZQpbEMZ/n/Gwet6p5bwh4X1uyFUcwk/yyHNmEol8w2BwZg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-13T12:19:26Z"
  mac: ENC[AES256_GCM,data:y+WIoK333427wssvr7BlXWlrvsmc+MKB1cedzILEb8bVDJSQlETuyfEEwEFSJZAPd/yGYEHxEvxvPYNNBt2Bla/68kSJOT2r8mMFmALkjl9zf7z+y4vOOEv1SBwxjeMGePDLhTs1jYFrbtvOVSDRdcO6jviNZH4Rc3MTrKMrZzc=,iv:afdS+mHQ3CyvkFrvVsPz9ZVr6oipzTa8+NQ9CzBKEe4=,tag:o+3S4SY+bj2ZrcXysKBsjQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
