apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  UNIFI_API_KEY: ENC[AES256_GCM,data:fe1HAE5JBOZEHisOELAOQBrXPS5KXHiOBlHCA/tW3/4=,iv:LISawjLAbd9lZ6EgON7ovzoAqhJ3gVv/Qoekkykxfes=,tag:JDz4YjM4v7131z/CbxAl8g==,type:str]
sops:
  age:
    - recipient: age1yzx80evlzvlvmepvta9mscwg8wkwhnky8mla5q2qsjd5afp8nyfstw5x5h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMHNHV1hhZzN1SmdKd094
        Z0tLMDFlQktPd2NnVWRVVXdWNzJ3RVp5SENBCkwyNFNZN2lhVzdPUFU2TkVaYjNj
        KzFEQWIvbTR1Vktjb3owTEp5amhsR0EKLS0tIEpSaXJRdmhROWp6Wkp2T01UaUY5
        MnllWEhic05EVXRNZ21LQTJZR08wVnMK7nJfuS1CgfMFEcN/qe6uP1L1eTQUp1KY
        JFNhD3NlEf+UOOUps4dQ2qGVU6z4tQKOXkdZsp7Vd/0uZZBv2sLEPA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-13T12:12:33Z"
  mac: ENC[AES256_GCM,data:9qScfycvpUxpGBEB12ES77fzs3d/gVuANKpuTIMimhmU38dV9kf0ebTX14yVqe9ZHvCTxgfR6b62h8SlkogYKyXm1AfkjSdKZ1a+E22NrcOYQPDTpBmIfpwsWFlkl5fZz19NUIFABwIrPpXEwRMT7ehm1abUzUQ76vALdl9TOwU=,iv:/qSmfrhieUoYm3cRyIrBzGjDqbnLiUDlz5DO+LC0aJY=,tag:EI2LdtnmtL2t/330gvyZGQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
