apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:3Ld55cI+a2Ii7yvUWViwNc11dUrpm+9jZZFStp+aDbcXkSgDprDp4Q==,iv:eyKVP7YgH844uqp9QDM5wnDpTs/Zz2hz15jOYNngLrk=,tag:dFmB8CMNOeV8lhSB6C6vTQ==,type:str]
sops:
  age:
    - recipient: age1yzx80evlzvlvmepvta9mscwg8wkwhnky8mla5q2qsjd5afp8nyfstw5x5h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdnlVaW0xdCs3QzdJeFp2
        ZVJ3SS84Zy9JK0NlM1hlYnZpaERNQmIxeDBrClpGUitiWlZNYkVhSlQvWmZyRHRj
        dVFvc1RaUStnZThaV09NdFVvd2dkNG8KLS0tIFhUMWNlV2g0dStCVWh5SmZja0NX
        d09lYzdCM1dhYWRoYlIvWjNzNktRK0EK/qYvJ7h+PaWEzDicdc34DT+104hFqLZl
        rAvLBCjkSBo926lTBenpu2j01JssjSH98yfLsbOJQg+5+seyEUWhvQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T09:40:18Z"
  mac: ENC[AES256_GCM,data:1N/1GCmqhHKkwlUOMVMslWY9yjiN3S2hu3RS9FncEPMEkGcBJSnqCzvNsswoLmiuNar9ImaiXQQvvXHAnJJfbIxqbMhqtlhSgbSjZpWBy4JoaTM4UtWjLgzUeuykt5aanlw5MsvqoKOBlXB7LPVFY6JGBkswJGW+JHW6ZRUoo8U=,iv:VmKy9uT8rPza+o6bENdrEo8ZIQGdIEpRqBOayJQrCDU=,tag:B7MNJCa52/XqXfDy9yE9XA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
