apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Jxl2JyaXgs939No0P/BcgGjpk/PVhvtcYyS2PV9jLQ/9025wdBe6Sg==,iv:j4eCvArBvKcCgmKwvXasXNBn8tmilsnhjDbpnGZ2+bw=,tag:SKcAQXoHUvmwQqtbfqB3KA==,type:str]
sops:
  age:
    - recipient: age1yzx80evlzvlvmepvta9mscwg8wkwhnky8mla5q2qsjd5afp8nyfstw5x5h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Z1pndkR5aVFhcEY5YXc2
        Vjh2bk5yK2E1NWZJZ0pCM01BV2R3RXRSa2lzCkJGRnNYeFVkN3RjbjZNZmNHY29R
        U1FEbEptVlE5UThramJKYjBRcmRGTDAKLS0tIEovZ1Q5V2grVHQwL0RMdWdsVDhk
        Y1oxRDdXei8xbnFxbVZlWDY0QkcxNjQKilZ7bLtJdcQofShTry5lujsFCa2YOli/
        4ys33ZEW2akPKTqnD6batMh300X0+YKoN+VEDiqMmuUdfRBmy91mXA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-13T08:17:47Z"
  mac: ENC[AES256_GCM,data:215gvNhikG+ISROaVwtFoAiVWyGrOQ7G/bidnWHsRbNJMKTzWy95+ri91FHIOcT8wlrIeUb6IrBhgb7Z5BCMqk3nJTGqKrs7PpcOF/QnR/NLnxHbL7nz6tPctBpIyt0+sJw3upm7G6ZDYuxGp2rWhpr+gaRfVmBHC9XRP7WqJ2Q=,iv:zahMBfxH03VnMjqKRHh5rtj9EgNGXC+PRpaMQospdW0=,tag:/OauATXZsXxE0CvV8FFrfg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
